//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SECURITY_ROLE
    {
        public int Role_ID { get; set; }
        public int Model_ID { get; set; }
        public Nullable<int> Model_PrivilegeID { get; set; }
        public int Model_AccessPermission { get; set; }
        public int Model_IsExplicit { get; set; }
        public int Entity_ID { get; set; }
        public Nullable<int> Entity_PrivilegeID { get; set; }
        public int Entity_AccessPermission { get; set; }
        public int Entity_IsExplicit { get; set; }
        public Nullable<int> MemberType_ID { get; set; }
        public Nullable<int> MemberType_PrivilegeID { get; set; }
        public int MemberType_AccessPermission { get; set; }
        public int MemberType_IsExplicit { get; set; }
        public int Attribute_ID { get; set; }
        public int Attribute_PrivilegeID { get; set; }
        public int Attribute_AccessPermission { get; set; }
        public int Attribute_IsExplicit { get; set; }
    }
}
