//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_BUSINESSRULES_ATTRIBUTE_INHERITANCE_HIERARCHY
    {
        public int ParentModelID { get; set; }
        public int ParentEntityID { get; set; }
        public string ParentEntityName { get; set; }
        public string ParentAttributeName { get; set; }
        public string ParentAttributeColumnName { get; set; }
        public int ChildEntityID { get; set; }
        public string ChildEntityName { get; set; }
        public string ChildAttributeName { get; set; }
        public string ChildAttributeColumnName { get; set; }
        public byte Attribute_MemberType_ID { get; set; }
    }
}
