//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SCHEMA_MODELS
    {
        public int Model_ID { get; set; }
        public System.Guid Model_MUID { get; set; }
        public string Model_Name { get; set; }
        public string Model_Label { get; set; }
        public string Model_Description { get; set; }
        public int Version_ID { get; set; }
        public System.Guid Version_MUID { get; set; }
        public string Version_Name { get; set; }
        public int Version_Number { get; set; }
        public string Version_Description { get; set; }
        public int Version_UserIDCreated { get; set; }
        public string Version_UserNameCreated { get; set; }
        public System.DateTime Version_DateCreated { get; set; }
        public int Version_UserIDUpdated { get; set; }
        public string Version_UserNameUpdated { get; set; }
        public System.DateTime Version_DateUpdated { get; set; }
        public int Version_StatusID { get; set; }
        public string Version_Status { get; set; }
        public Nullable<int> Version_FlagID { get; set; }
        public string Version_FlagName { get; set; }
        public Nullable<int> Version_SourceVersionID { get; set; }
        public Nullable<int> Entity_ID { get; set; }
        public Nullable<System.Guid> Entity_MUID { get; set; }
        public string Entity_Name { get; set; }
        public string Entity_Label { get; set; }
        public Nullable<bool> Entity_IsBase { get; set; }
        public int Entity_HasHierarchy { get; set; }
        public Nullable<int> Entity_UserIDCreated { get; set; }
        public string Entity_UserNameCreated { get; set; }
        public Nullable<System.DateTime> Entity_DateCreated { get; set; }
        public Nullable<int> Entity_UserIDUpdated { get; set; }
        public string Entity_UserNameUpdated { get; set; }
        public Nullable<System.DateTime> Entity_DateUpdated { get; set; }
        public Nullable<int> Entity_VersionIDUpdated { get; set; }
        public string Entity_Table { get; set; }
        public string Entity_HierarchyTable { get; set; }
        public string Entity_HierarchyParentTable { get; set; }
        public string Entity_CollectionTable { get; set; }
        public string Entity_CollectionMemberTable { get; set; }
        public Nullable<int> Hierarchy_ID { get; set; }
        public Nullable<System.Guid> Hierarchy_MUID { get; set; }
        public string Hierarchy_Name { get; set; }
        public string Hierarchy_Label { get; set; }
        public Nullable<int> HierarchyType_ID { get; set; }
        public Nullable<bool> Hierarchy_IsMandatory { get; set; }
        public Nullable<int> Hierarchy_UserIDCreated { get; set; }
        public string Hierarchy_UserNameCreated { get; set; }
        public Nullable<System.DateTime> Hierarchy_DateCreated { get; set; }
        public Nullable<int> Hierarchy_UserIDUpdated { get; set; }
        public string Hierarchy_UserNameUpdated { get; set; }
        public Nullable<System.DateTime> Hierarchy_DateUpdated { get; set; }
        public Nullable<int> Hierarchy_VersionIDUpdated { get; set; }
        public int MemberType_ID { get; set; }
        public string MemberType_Name { get; set; }
        public string MemberType_Label { get; set; }
    }
}
