//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SECURITY_ROLE_ACCESSCONTROL_FUNCTIONAL
    {
        public int RoleAccess_ID { get; set; }
        public System.Guid RoleAccess_MUID { get; set; }
        public int Role_ID { get; set; }
        public int Principal_ID { get; set; }
        public Nullable<System.Guid> Principal_MUID { get; set; }
        public int PrincipalType_ID { get; set; }
        public string Principal_Name { get; set; }
        public byte Function_ID { get; set; }
        public string Function_Name { get; set; }
        public System.DateTime EnterDTM { get; set; }
        public int EnterUserID { get; set; }
        public Nullable<System.Guid> EnterUserMUID { get; set; }
        public string EnterUserName { get; set; }
        public System.DateTime LastChgDTM { get; set; }
        public int LastChgUserID { get; set; }
        public Nullable<System.Guid> LastChgUserMUID { get; set; }
        public string LastChgUserName { get; set; }
    }
}
