//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_USERGROUP_USERS
    {
        public int UserGroup_ID { get; set; }
        public System.Guid UserGroup_MUID { get; set; }
        public string UserGroup_SID { get; set; }
        public string UserGroup_Name { get; set; }
        public int User_ID { get; set; }
        public System.Guid User_MUID { get; set; }
        public string User_SID { get; set; }
        public string User_Name { get; set; }
    }
}
