//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SECURITY_ROLE_MEMBER
    {
        public int Role_ID { get; set; }
        public Nullable<int> Entity_ID { get; set; }
        public int LeafOnly { get; set; }
        public int Version_ID { get; set; }
        public int Hierarchy_ID { get; set; }
        public int HierarchyType_ID { get; set; }
        public bool IsInitialized { get; set; }
    }
}
