//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SECURITY_ROLE_ACCESSCONTROL_MEMBER
    {
        public int RoleAccess_ID { get; set; }
        public System.Guid RoleAccess_MUID { get; set; }
        public int Privilege_ID { get; set; }
        public byte AccessPermission { get; set; }
        public Nullable<int> Model_ID { get; set; }
        public Nullable<System.Guid> Model_MUID { get; set; }
        public string Model_Name { get; set; }
        public int IsModelAdministrator { get; set; }
        public int Version_ID { get; set; }
        public Nullable<System.Guid> Version_MUID { get; set; }
        public string Version_Name { get; set; }
        public byte HierarchyType_ID { get; set; }
        public Nullable<int> Hierarchy_ID { get; set; }
        public Nullable<System.Guid> Hierarchy_MUID { get; set; }
        public string Hierarchy_Name { get; set; }
        public int Entity_ID { get; set; }
        public Nullable<System.Guid> Entity_MUID { get; set; }
        public string Entity_Name { get; set; }
        public byte MemberType_ID { get; set; }
        public int Member_ID { get; set; }
        public int Role_ID { get; set; }
        public int PrincipalType_ID { get; set; }
        public int Principal_ID { get; set; }
        public Nullable<System.Guid> Principal_MUID { get; set; }
        public string Principal_Name { get; set; }
        public int EnterUserID { get; set; }
        public Nullable<System.Guid> EnterUserMUID { get; set; }
        public string EnterUser { get; set; }
        public System.DateTime EnterDTM { get; set; }
        public int LastChgUserID { get; set; }
        public Nullable<System.Guid> LastChgUserMUID { get; set; }
        public string LastChgUser { get; set; }
        public System.DateTime LastChgDTM { get; set; }
    }
}
