//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SCHEMA_BUSINESSRULE_PROPERTIES_ATTRIBUTES
    {
        public int Property_ID { get; set; }
        public int BusinessRule_ID { get; set; }
        public System.Guid BusinessRule_MUID { get; set; }
        public string BusinessRule_Name { get; set; }
        public int BusinessRule_Status { get; set; }
        public int Item_ID { get; set; }
        public System.Guid Item_MUID { get; set; }
        public int Item_AppliesTo_ID { get; set; }
        public int PropertyType_ID { get; set; }
        public string Property_Value { get; set; }
        public int Property_Sequence { get; set; }
        public bool Property_IsLeftHandSide { get; set; }
        public Nullable<int> Property_Parent_ID { get; set; }
        public Nullable<int> Property_Parent_PropertyType_ID { get; set; }
        public Nullable<int> Property_Parent_PropertyName_ID { get; set; }
        public int Model_ID { get; set; }
        public System.Guid Model_MUID { get; set; }
        public int Attribute_Entity_ID { get; set; }
        public System.Guid Attribute_Entity_MUID { get; set; }
        public string Attribute_Entity_Name { get; set; }
        public int Attribute_ID { get; set; }
        public System.Guid Attribute_MUID { get; set; }
        public string Attribute_Name { get; set; }
        public string Attribute_Column { get; set; }
        public byte Attribute_MemberType_ID { get; set; }
        public Nullable<int> Attribute_DBAEntity_ID { get; set; }
        public Nullable<System.Guid> Attribute_DBAEntity_MUID { get; set; }
        public string Attribute_DBAEntity_Name { get; set; }
        public int Attribute_ChangeTrackingGroup { get; set; }
    }
}
