//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SCHEMA_SYSTEMSETTINGS
    {
        public int ID { get; set; }
        public System.Guid MUID { get; set; }
        public string SettingName { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public byte SettingType_ID { get; set; }
        public string SettingType_Name { get; set; }
        public byte DataType_ID { get; set; }
        public string DataType_Name { get; set; }
        public string SettingValue { get; set; }
        public string SettingValueDomainName { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public bool IsVisible { get; set; }
        public int DisplaySequence { get; set; }
        public int SystemSettingGroup_ID { get; set; }
    }
}
