//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SECURITY_USER_ENTITY
    {
        public int User_ID { get; set; }
        public Nullable<int> IsSyncTarget { get; set; }
        public int ID { get; set; }
        public Nullable<int> Privilege_ID { get; set; }
        public Nullable<int> AccessPermission { get; set; }
    }
}
