//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SCHEMA_BUSINESSRULE_ITEMTYPES
    {
        public int AppliesTo_ID { get; set; }
        public int ApplyTo_ID { get; set; }
        public int ApplyToCategoryID { get; set; }
        public string ApplyToCategory { get; set; }
        public int BRTypeID { get; set; }
        public int BRSubTypeID { get; set; }
        public int BRSubTypeIsVisible { get; set; }
        public int BRItemType_ID { get; set; }
        public int DisplaySequence { get; set; }
        public int DisplaySubSequence { get; set; }
    }
}
