//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SCHEMA_ENTITY
    {
        public int ID { get; set; }
        public int Entity_ID { get; set; }
        public System.Guid MUID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsBase { get; set; }
        public string EntityTable { get; set; }
        public string HierarchyTable { get; set; }
        public string HierarchyParentTable { get; set; }
        public string CollectionTable { get; set; }
        public string CollectionMemberTable { get; set; }
        public string StagingBase { get; set; }
        public string StagingLeafTable { get; set; }
        public string StagingConsolidatedTable { get; set; }
        public string StagingRelationshipTable { get; set; }
        public int Model_ID { get; set; }
        public System.Guid Model_MUID { get; set; }
        public string Model_Name { get; set; }
        public int EnteredUser_ID { get; set; }
        public Nullable<System.Guid> EnteredUser_MUID { get; set; }
        public string EnteredUser_UserName { get; set; }
        public System.DateTime EnteredUser_DTM { get; set; }
        public int LastChgUser_ID { get; set; }
        public Nullable<System.Guid> LastChgUser_MUID { get; set; }
        public string LastChgUser_UserName { get; set; }
        public System.DateTime LastChgUser_DTM { get; set; }
        public int IsCodeGenerationEnabled { get; set; }
        public Nullable<int> CodeGenerationSeed { get; set; }
        public byte DataCompression { get; set; }
        public byte TransactionLogType { get; set; }
        public bool RequireApproval { get; set; }
    }
}
