//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_EntityStagingBatchesAllProcessedExceptCleared
    {
        public int Batch_ID { get; set; }
        public string BatchTag { get; set; }
        public Nullable<int> Entity_ID { get; set; }
        public Nullable<byte> MemberTypeID { get; set; }
        public System.Guid Version_MUID { get; set; }
        public string VersionName { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> ProcessStart { get; set; }
        public Nullable<System.DateTime> ProcessEnd { get; set; }
        public Nullable<int> ProcessUserID { get; set; }
        public Nullable<int> TotalRows { get; set; }
        public Nullable<int> RowsInError { get; set; }
        public int Model_ID { get; set; }
    }
}
