//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SECURITY_USER_MEMBER
    {
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Privilege_ID { get; set; }
        public Nullable<int> AccessPermission { get; set; }
        public int Version_ID { get; set; }
        public int Entity_ID { get; set; }
        public Nullable<int> Hierarchy_ID { get; set; }
        public byte HierarchyType_ID { get; set; }
        public int Member_ID { get; set; }
        public byte MemberType_ID { get; set; }
        public bool IsMapped { get; set; }
    }
}
