//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SCHEMA_HIERARCHY_DERIVED_LEVELS
    {
        public int Model_ID { get; set; }
        public System.Guid Model_MUID { get; set; }
        public string Model_Name { get; set; }
        public int Hierarchy_ID { get; set; }
        public System.Guid Hierarchy_MUID { get; set; }
        public string Hierarchy_Name { get; set; }
        public int ID { get; set; }
        public System.Guid MUID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public int ForeignType_ID { get; set; }
        public string ForeignType_Name { get; set; }
        public Nullable<int> Foreign_ID { get; set; }
        public Nullable<System.Guid> Foreign_MUID { get; set; }
        public string Foreign_Name { get; set; }
        public Nullable<int> ForeignEntity_ID { get; set; }
        public Nullable<System.Guid> ForeignEntity_MUID { get; set; }
        public string ForeignEntity_Name { get; set; }
        public Nullable<int> Entity_ID { get; set; }
        public Nullable<System.Guid> Entity_MUID { get; set; }
        public string Entity_Name { get; set; }
        public Nullable<int> ManyToManyChildAttribute_ID { get; set; }
        public Nullable<System.Guid> ManyToManyChildAttribute_MUID { get; set; }
        public string ManyToManyChildAttribute_Name { get; set; }
        public Nullable<int> LevelNumber { get; set; }
        public Nullable<int> Level_ID { get; set; }
        public bool IsLevelVisible { get; set; }
        public int MemberType_ID { get; set; }
        public string MemberType_Name { get; set; }
        public int IsRecursive { get; set; }
        public int Detail_EnteredUser_ID { get; set; }
        public Nullable<System.Guid> Detail_EnteredUser_MUID { get; set; }
        public string Detail_EnteredUser_UserName { get; set; }
        public System.DateTime Detail_EnteredUser_DTM { get; set; }
        public int Detail_LastChgUser_ID { get; set; }
        public Nullable<System.Guid> Detail_LastChgUser_MUID { get; set; }
        public string Detail_LastChgUser_UserName { get; set; }
        public System.DateTime Detail_LastChgUser_DTM { get; set; }
    }
}
