//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_BUSINESSRULES_HIERARCHY_CHANGEVALUE_INHERITANCE
    {
        public int ModelID { get; set; }
        public int EntityID { get; set; }
        public string EntityName { get; set; }
        public string AttributeName { get; set; }
        public string AttributeColumnName { get; set; }
        public int HierarchyID { get; set; }
        public string HierarchyName { get; set; }
    }
}
