//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SCHEMA_BUSINESSRULE_PROPERTIES
    {
        public int Property_ID { get; set; }
        public int BusinessRule_ID { get; set; }
        public System.Guid BusinessRule_MUID { get; set; }
        public string BusinessRule_Name { get; set; }
        public int BusinessRule_Status { get; set; }
        public int LogicalOperator_ID { get; set; }
        public System.Guid LogicalOperator_MUID { get; set; }
        public string LogicalOperator_Name { get; set; }
        public int Item_ID { get; set; }
        public System.Guid Item_MUID { get; set; }
        public string Item_Text { get; set; }
        public int Item_Sequence { get; set; }
        public int Item_AppliesTo_ID { get; set; }
        public int PropertyType_ID { get; set; }
        public string PropertyType_Name { get; set; }
        public int PropertyName_ID { get; set; }
        public string PropertyName_Name { get; set; }
        public string Property_Value { get; set; }
        public int Property_Sequence { get; set; }
        public bool Property_IsLeftHandSide { get; set; }
        public Nullable<int> Property_Parent_ID { get; set; }
        public Nullable<bool> Property_SuppressText { get; set; }
    }
}
