//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_SYSTEM_SECURITY_USER_ROLE
    {
        public Nullable<int> User_ID { get; set; }
        public int Role_ID { get; set; }
        public int IsUserGroupAssignment { get; set; }
    }
}
